name: First Workflow
on: workflow_dispatch
jobs:
  greet-job:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting the world
        run: echo "Hello World"
      - name: Tata bye Bye
        run: echo "Bye Bye Everyone"
